#!/usr/bin/env python


import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(abs_tolerance = 1.0e-4,
      ignore_sign = True) # all lines

test.run(['sososc7.inp'], ['sososc7.mol'],
         f={'sososc7.inp': f}, args='sososc7.inp')

sys.exit(test.return_code)
