      INTEGER AND88(8,8),OR88(8,8),EOR88(8,8)
      COMMON /WESGTO/ ALPHA(MXPRIM),CONT(MXPRIM),
     1   CENTOP(3),FMULT(8),PTAND(8,8),
     +   AND88,OR88,EOR88,
     +   CTRAN(MXCORB,8),JTRAN(MXCORB),ITRAN(MXCORB,8),
     +   MAXLOP,MAXLOT,KMAX,NMAX,
     2   KHKT(4),MULT(8),ISYTYP(3),ITYPEX(4,10),
     +   NHKT(MXSHEL),MULBAS(MXSHEL), CENT(MXSHEL,3,2),
     3   NUCO(MXSHEL), JSTRT(MXSHEL),NSTRT(MXSHEL),
     +   NBASSS(8),IFXYZ(3),NTAP,LUT
