C
C   possible extension to WESINF: EMCWES(2,2); IPRINP ( for READIW)
C                                 IPRCI ( for WESCI )
C
      PARAMETER (MAX_CIROOTS = 40)
      LOGICAL NONADI, TRAMOM, WAVEOV, SYMORT, SHAKE, MOMTYP(10),
     1        REDUCE, FROZEN, OCEINT, CICALC
      REAL*8  NUCMASS
      COMMON /WESINF/ DISPL, POTNUV(2), EMCWES(2,2), NUCMASS(2),
     1   SPIN1,  SPIN2, DELQ(3,100), CENTOP(3),
     2   NCONF1, NCONF2, LSYM1,  LSYM2,  LSPIN1, LSPIN2, NSTAT2, NGEOM,
     3   ISTATV(2,2), IRDMOW, NMAXD, ICIORD(MAX_CIROOTS),
     4   IPRDEF, IPRNAD, IPRTRM, IPRBIO, IPRMLC, IPRSHK, IACFLG, IACSYM,
     5   IACORB, REDUCE, NONADI, TRAMOM, MOMTYP, WAVEOV, SYMORT, SHAKE,
     6   FROZEN, OCEINT, CICALC
