C
CPFP 12/2015 Added the stuff for SOSOSC
C
      PARAMETER (NOV=200, NOC=20, NCONT=5, INSPN=45, NPEE=5000)
      PARAMETER (NLABOC=20, NLABVI=200, NTHREE=3)
      INTEGER NVSET,NV2LOC,NO2LOC,NOCLAB,NVILAB
C      INTEGER NFTRLV,NCTRLV,NFTRLO,NCTRLO
      INTEGER INDEXT,INCONT,NCSSCC,NCTERM,NCMTHD,IATIJC
C      DOUBLE PRECISION SSCCPE(NPEE,NCONT), SSCCNI(INSPN,NCONT),THRSLO
      CHARACTER TABOCL(NLABOC)*8,TABVIL(NLABVI)*8
      LOGICAL ABALOC, FOSOCC, FBOVIR, FBSETV, FBSTVO, MULLOC
      LOGICAL FBOCIN, LABOCC, LABVIR, FBOOCC, PIPEKL
C
      COMMON /LOCINF/ ABALOC, FOSOCC, FBOVIR, FBSETV, FBSTVO, MULLOC,
     &                FBOCIN, LABOCC, LABVIR, FBOOCC,  NVSET, PIPEKL,
     &                NTVI2L(NOV), NV2LOC, NO2LOC, NVILAB, NOCLAB,
     &                NTOC2L(NOC), TABOCL, TABVIL, NCSSCC, NCTERM,
     &                NCMTHD, INDEXT, INCONT, IATIJC,
C     &                NFTRLV, NCTRLV, NFTRLO, NCTRLO,
     &                SSCCPE(NPEE,NCONT), SSCCNI(INSPN,NCONT), THRSLO
Cend-PFP
